title: Marie's Homepage
page-top-title: Marie Gerantonis
top-section-bg-text: learning designer, trainer & assessor
home-subtitle: Marie Gerantonis Name&ensp;
copyright-text: '&copy; marie gerantonis 2026. All Rights Reserved.'
